<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/font-awesome-4.3.0.min.css">

    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/font-awesome-4.3.0.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/3wa-resto.css">
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/ui-button.css">
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/ui-form.css">
    <link rel="stylesheet" href="/developpement/RESTAURANT/application/www/css/ui-table.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <!-- JavaScript de l'application -->
    <script src="/developpement/RESTAURANT/application/www/js/utilities.js"></script>
    <script src="/developpement/RESTAURANT/application/www/js/classes/FormValidator.class.js"></script>
</head>
<body>

    <!-- En-tête commune -->
    <header>
        <h1>
            <a href="/developpement/RESTAURANT/index.php">
                <img src="/developpement/RESTAURANT/application/www/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
            </a>
        </h1>
    </header>

    <!-- Interface utilisateur -->
    <nav class="user-interface">
        <ul class="link-list">
                            <li>
                    <a class="button button-primary" href="/developpement/RESTAURANT/index.php/booking">Réserver</a>
                    <a class="button button-primary" href="/developpement/RESTAURANT/index.php/order">Commander</a>
                </li>
                <li class="layout-right">
                    <p class="welcome">Bonjour <strong>a a</strong> !</p>
                    <a class="button button-primary" href="/developpement/RESTAURANT/index.php/user/logout">Déconnexion</a>
                </li>
                    </ul>
    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <h2><i class="fa fa-star"></i> Commande payée</h2>

<h3>Merci d'avoir commandé au 3WA Restaurant !</h3>

<p data-order-step="success">Votre commande a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
<p class="layout-center"><img alt="Commande payée" src="/developpement/RESTAURANT/application/www/images/success.gif"></p>

<a class="button button-primary" href="/developpement/RESTAURANT/index.php">Accueil</a>


<!-- Classes de gestion du formulaire de commande -->
<!-- Ce code JavaScript n'est chargé QUE depuis l'URL /order/payment/success -->
<script src="/developpement/RESTAURANT/application/www/js/classes/BasketSession.class.js"></script>
<script src="/developpement/RESTAURANT/application/www/js/classes/OrderForm.class.js"></script>    </main>

    <!-- Pied de page commun -->
    <footer>
        <ul class="link-list">
            <li><img src="/developpement/RESTAURANT/application/www/images/payment/visa.png" alt="Visa"></li>
            <li><img src="/developpement/RESTAURANT/application/www/images/payment/mastercard.png" alt="MasterCard"></li>
            <li><img src="/developpement/RESTAURANT/application/www/images/payment/paypal.png" alt="PayPal"></li>
        </ul>
        <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
    </footer>

    <!-- Code principal JavaScript de l'application -->
    <script src="/developpement/RESTAURANT/application/www/js/main.js"></script>
</body>
</html>
