<h2><i class="fa fa-file-text-o"></i> Article</h2>

<section class="post">
    <h3><?= htmlspecialchars($post['Title']) ?></h3>
    <article><?= nl2br(htmlspecialchars($post['Content'])) ?></article>
    <small>
        Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
        le <?= htmlspecialchars($post['CreationTimesTamp']) ?>
    </small>
</section>

<hr>

<ul class="comment-list">
  <?php foreach($comments as $comment): ?>
        <li class="comment">
            <h4><i class="fa fa-comment"></i> Rédigé par <?= htmlspecialchars($comment['NickName']) ?></h4>
            <article><?= htmlspecialchars($comment['Contents']) ?></article>
        </li>
    <?php endforeach; ?>
</ul>

<hr>

<form class="generic-form" action="add_comment.php" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="Post_Id" value="<?= intval($_GET['id']) ?>">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="NickName">Pseudo :</label>
                <input type="text" id="NickName" name="NickName">
            </li>
            <li>
                <label class="textarea" for="Contents">Commentaire :</label>
                <textarea id="Contents" name="Contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>
