<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/order-form.css">
</head>
<body>
    <section>
        <h1>Bons de commande</h1>

        <table class="standard-table">
            <caption>Liste des commandes</caption>
            <thead>
                <tr>
                    <th>Commande</th>
                    <th>Date de la commande</th>
                    <th>Date de livraison</th>
                    <th>Statut</th>
                </tr>
            </thead>
            <tbody>



            <?php foreach ($orders as $value) { ?>
                  <tr>
                    <td><a href="order-form.php?orderNumber=<?=$value['orderNumber']?>"> <?=$value['orderNumber']?></a>
                    </td>
                    <td><?=$value['orderDate']?></td>
                    <td><?=$value['shippedDate']?></td>
                    <td><?=$value['status']?></td>
                  </tr>
              <?php  }  ?>
                            </tbody>
        </table>
    </section>
</body>
</html>
