<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/order-form.css">
</head>
<body>
    <section>
        <h1>Bons de commande</h1>

        <a href="index.php">Retourner à l'accueil</a>

        <!-- Etiquette avec fiche client -->
        <article class="order-form-customer">
            <h2></h2>
            <h3></h3>
            <p></p>
            <p></p>
            <p></p>
        </article>
        <hr>

        <!-- Le bon de commande -->
        <table class="standard-table">
            <caption></caption>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th class="money-column">Prix Unitaire</th>
                    <th>Quantité</th>
                    <th class="money-column">Prix Total</th>
                </tr>
            </thead>
            <!-- Un footer de tableau HTML se positionne AVANT le body ! -->
            <tfoot>
              <tr>
                <th colspan="3">Montant Total HT</th>
                  <th><?= number_format($totalAmount, 2) ?> €</th>
              </tr>
              <tr>
                  <th colspan="3">TVA (20 %)</th>
                  <th><?= number_format($totalAmount * 0.20, 2) ?> €</th>
              </tr>
                <tr>
                  <th colspan="3">Montant Total TTC</th>
                  <th><?= number_format($totalAmount * 1.20, 2) ?> €</th>
              </tr>
            </tfoot>
            <tbody>
              <?php foreach($orderLines as $orderLine): ?>

              <tr>
                <td><?= $orderLine['productName'] ?></td>
                  <td class="money-column"><?= number_format($orderLine['priceEach'], 2) ?> €</td>
                  <td><?= $orderLine['quantityOrdered'] ?></td>
                  <td class="money-column"><?= number_format($orderLine['totalPrice'], 2) ?> €</td>
              </tr>

          <?php endforeach ?>

                            </tbody>
        </table>
    </section>
</body>
</html>
